config/routes.rb
require 'sidekiq/web'

class AdminConstraint
  def self.matches?(request)
    return false unless request.session[:user_id]
    user = User.find request.session[:user_id]
    user && user.admin?
  end
end

class Sitedomain
  def self.matches?(request)
    request.host =~ /^[a-zA-Z0-9\-]+\.#{Regexp.escape APP_CONFIG["host"]}$/ or request.host !~ /#{Regexp.escape APP_CONFIG["host"]}$/
  end
end

Writings::Application.routes.draw do
  constraints :host => APP_CONFIG["host"] do
    root :to => 'home#index'
    get 'feature-manager', :to => 'home#feature-manager'
    get 'feature-editor', :to => 'home#feature-editor'
    get 'feature-history', :to => 'home#feature-history'
    get 'about', :to => 'home#about'
    get 'signup' => 'users#new', :as => :signup
    get 'login' => 'user_sessions#new', :as => :login
    delete 'logout' => 'user_sessions#destroy', :as => :logout

    resources :password_resets, :only => [:new, :create, :edit, :update]

    resources :users, :only => [:create]
    resources :user_sessions, :only => [:create]

    resource :account, :only => [:show, :update]

    resources :invoices, :only => [:index, :new, :create, :show, :destroy] do
      collection do
        post :alipay_notify
      end
    end
    resources :spaces, :only => [:new, :create]

    scope '/~:space_id', :module => 'dashboard', :as => 'dashboard' do
      root :to => 'articles#index'

      resource :billing, :only => [:show]
      resources :orders, :only => [:index, :new, :create, :show, :destroy] do
        collection do
          post :alipay_notify
        end
      end

      resource :settings, :only => [:show, :update]
      resources :members, :only => [:index, :destroy]
      resources :invitations, :only => [:show, :accept, :create, :destroy] do
        member do
          put :resend
          put :accept
          post :join
        end
      end

      resources :categories, :only => [:create, :edit, :update, :destroy]
      get '/uncategorized', :as => 'articles_uncategorized', :to => 'articles#uncategorized'
      get '/trashed', :as => 'articles_trashed', :to => 'articles#trashed'
      get '/categorized/:category_id', :as => 'articles_categorized', :to => 'articles#categorized'
      resources :articles, :only => [:new, :show, :create, :edit, :update, :destroy] do
        collection do
          delete 'trashed', :to => 'articles#empty_trash'
          put :batch_category
          put :batch_trash
          put :batch_publish
          put :batch_draft
          put :batch_restore
          put :batch_destroy
        end

        member do
          get :status
          put :restore
        end

        resources :versions, :only => [:index, :show] do
          member do
            put :restore
          end
        end
      end

      resources :export_tasks, :only => [:index, :create, :show] do
        member do
          get :download
        end
      end
      resources :import_tasks, :only => [:index, :create, :show, :destroy] do
        member do
          post :confirm
        end
      end
      resources :attachments, :only => [:index, :create, :destroy]
    end

    constraints(AdminConstraint) do
      namespace :admin do
        root :to => 'dashboard#show'
        resources :articles, :only => [:index, :show]
        resources :users, :only => [:index, :show]
        resources :spaces, :only => [:index, :show]
        resources :attachments, :only => [:index]
        resources :orders, :only => [:index, :show]
        resources :alipay_notifies, :only => [:index, :show]
      end

      mount Sidekiq::Web => '/sidekiq'
    end
  end

  constraints(Sitedomain) do
    scope :module => 'site', :as => 'site' do
      root :to => 'articles#index'
      get 'feed', :to => 'articles#feed', :as => :feed
      get 'articles/:id(-:urlname)', :to => 'articles#show', :as => :article, :constraints => { :id => /[a-zA-Z0-9]+/ }
      resources :authors, :only => [:index, :show]
      resources :archives, :only => [:index]
      resources :categories, :only => [:index, :show] do
        member do
          get :feed
        end
      end
    end
  end

  if Rails.env.development?
    namespace :ui do
      get 'dashboard/:action', :controller => 'dashboard'
      get 'site/:action', :controller => 'site'
    end
  end

  if Rails.env.production?
    get '*a', :to => 'errors#not_found'
  end
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < Admin::BaseController
  def index
    @articles_scope = Article.scoped
    if params[:name]
      @space = Space.where(:name => params[:name]).first
      @articles_scope = @articles_scope.where(:space_id => (@space ? @space.id : nil))
    end

    @articles = case params[:tab]
                when 'all'
                  @articles_scope.desc(:updated_at).includes(:space).page(params[:page]).per(25)
                else
                  @articles_scope.publish.desc(:published_at).includes(:space).page(params[:page]).per(25)
                end
  end

  def show
    @article = Article.find params[:id]
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def show
  end
end

app/controllers/dashboard/articles_controller.rb
class Dashboard::ArticlesController < Dashboard::BaseController
  before_filter :find_article, :only => [:show, :status, :edit, :update, :restore]
  before_filter :find_articles, :only => [:batch_trash, :batch_publish, :batch_draft, :batch_restore, :batch_destroy]
  before_filter :check_lock_status, :only => [:update]

  def index
    @articles = @space.articles.desc(:updated_at).page(params[:page]).per(15).untrash

    if params[:status].present?
      @articles = @articles.status(params[:status])
    elsif !@space.in_plan?(:free) && params[:query].present?
      query = params[:query].split.map { |string| Regexp.escape string }[0..2].join '|'
      @articles = @articles.where(:title => /#{query}/i)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def trashed
    @articles = @space.articles.desc(:updated_at).page(params[:page]).per(15).status('trash')
  end

  def show
    respond_to do |format|
      format.md { render :text => PandocRuby.convert(@article.body, { :from => 'html', :to => 'markdown+hard_line_breaks' }, 'atx-headers') }
    end
  end

  def new
    @article = @space.articles.new
    append_title @article.title
    render :edit, :layout => 'editor'
  end

  def create
    @article = @space.articles.new article_params.merge(:user => current_user, :last_edit_user => current_user)
    if @article.save
      @article.create_version

      render :article
    else
      render :json => { :message => @article.errors.full_messages.join }, :status => 400
    end
  end

  def status
  end

  def edit
    append_title @article.title

    render :layout => 'editor'
  end

  def update
    if @article.last_edit_user && @article.last_edit_user != current_user
      @article.create_version :user => @article.last_edit_user
    end

    if article_params[:save_count].to_i > @article.save_count
      if @article.update_attributes article_params.merge(:last_edit_user => current_user)

        if @article.save_count - @article.last_version_save_count >= 100
          @article.create_version :user => current_user
        end

        render :article
      else
        respond_to do |format|
          format.json { render :json => { :message => @article.errors.full_messages.join }, :status => 400 }
        end
      end
    else
      render :json => { :message => I18n.t('save_count_expired'), :code => 'save_count_expired' }, :status => 400
    end
  end

  def restore
    @article.update_attributes :status => :draft
    redirect_to :action => :edit, :id => @article
  end

  def empty_trash
    @space.articles.trash.destroy_all
  end

  def batch_trash
    @articles.untrash.update_all :status => 'trash', :updated_at => Time.now.utc

    render :batch_update
  end

  def batch_publish
    @articles.untrash.update_all :status => 'publish', :updated_at => Time.now.utc
    @articles.untrash.where(:published_at => nil).update_all :published_at => Time.now.utc

    render :batch_update
  end

  def batch_draft
    @articles.untrash.update_all :status => 'draft', :updated_at => Time.now.utc

    render :batch_update
  end

  def batch_restore
    @articles.trash.where(:status => 'trash').update_all :status => 'draft', :updated_at => Time.now.utc

    render :batch_update
  end

  def batch_destroy
    @articles.trash.destroy_all

    render :batch_update
  end

  private

  def find_article
    @article = @space.articles.find_by(:token => params[:id])
  end

  def find_articles
    @articles = @space.articles.where(:token.in => params[:ids])
  end

  def article_params
    base_params = params.require(:article).permit(:title, :body, :urlname, :status, :save_count)

    base_params
  end

  def check_lock_status
    if @article.locked? and !@article.locked_by?(current_user)
      locked_user = User.where(:id => @article.locked_by).first
      render :json => { :message => I18n.t('is_editing', :name => @article.locked_by_user.name ), :code => 'article_locked', :locked_user => { :name => locked_user.try(:name) } }, :status => 400
    else
      @article.lock_by(current_user)
    end
  end
end

app/controllers/dashboard/attachments_controller.rb
class Dashboard::AttachmentsController < Dashboard::BaseController
  def index
    @attachments = @space.attachments.desc(:created_at).page(params[:page]).per(25)
  end

  def create
    @attachment = @space.attachments.new attachment_params.merge(:user => current_user)

    if @attachment.save
      respond_to do |format|
        format.json
      end
    else
      respond_to do |format|
        format.json { render :json => { :message => @attachment.errors.full_messages.join }, :status => 400 }
      end
    end
  rescue CarrierWave::DownloadError
    respond_to do |format|
      format.json { render :json => { :message => I18n.t('errors.messages.fetch_error') }, :status => 400 }
    end
  end

  def destroy
    @attachment = @space.attachments.find params[:id]
    @attachment.destroy
  end

  private

  def attachment_params
    params.require(:attachment).permit(:file, :remote_file_url)
  end
end

app/controllers/dashboard/base_controller.rb
class Dashboard::BaseController < ApplicationController
  before_filter :require_logined
  before_filter :find_space, :require_space_access
  helper_method :is_creator?
  layout 'dashboard'

  private

  class AccessDenied < Exception
  end

  def find_space
    @space = Space.find_by :name => params[:space_id]
  end

  def require_space_access
    unless @space.user == current_user or (!@space.in_plan?(:free) && @space.members.include?(current_user))
      raise AccessDenied
    end
  end

  def require_creator
    unless is_creator?
      raise AccessDenied
    end
  end

  def is_creator?
    @space.user == current_user
  end
end

app/controllers/dashboard/billings_controller.rb
class Dashboard::BillingsController < Dashboard::BaseController
  before_filter :require_creator

  def show
    @orders = @space.orders.showable.desc(:created_at).limit(5)
  end
end

app/controllers/dashboard/export_tasks_controller.rb
class Dashboard::ExportTasksController < Dashboard::BaseController
  def index
  end

  def create
    task = ExportTask.create(
      :space    => @space,
      :format   => params[:export_task][:format],
      :user     => current_user
    )
    ExportTask.delay.perform_task(task.id.to_s)

    redirect_to :action => :show, :id => task
  end

  def show
    @export_task = @space.export_tasks.find params[:id]
  end

  def download
    @export_task = @space.export_tasks.success.find params[:id]
    send_file @export_task.path, :filename => @export_task.filename
  end
end

app/controllers/dashboard/import_tasks_controller.rb
class Dashboard::ImportTasksController < Dashboard::BaseController
  def index
  end

  def create
    @import_task = @space.import_tasks.create import_task_param.merge(:user => current_user)

    ImportTask.delay.perform_task(@import_task.id.to_s)
    redirect_to :action => :show, :id => @import_task
  end

  def show
    @import_task = @space.import_tasks.find params[:id]
  end

  def confirm
    @import_task = @space.import_tasks.where(:status => 'success').find params[:id]
    @import_task.confirm(params[:ids])
    @import_task.destroy
    redirect_to dashboard_root_path
  end

  private

  def import_task_param
    params.require(:import_task).permit(:format, :file)
  end
end

app/controllers/dashboard/invitations_controller.rb
class Dashboard::InvitationsController < Dashboard::BaseController
  before_filter :require_creator, :require_plan, :only => [:create, :destroy, :resend]
  skip_filter :require_logined, :require_space_access, :only => [:show, :accept, :join]

  def show
    @invitation = @space.invitations.find_by :token => params[:id]

    if logined? and @space.members.include?(current_user)
      redirect_to dashboard_root_url
    end
  end

  def create
    exists_emails = @space.members.map(&:email).map(&:downcase)

    @invitations = params[:emails].map { |email|
      if email.present? && !exists_emails.include?(email.downcase)
        @space.invitations.create :email => email, :message => params[:message]
      end
    }.compact.find_all { |invitation| invitation.persisted? }
  end

  def destroy
    @invitation = @space.invitations.find params[:id]
    @invitation.destroy
  end

  def resend
    @invitation = @space.invitations.find params[:id]
    @invitation.send_mail
  end

  def accept
    @invitation = @space.invitations.find_by :token => params[:id]
    unless @space.members.include? current_user
      @space.members << current_user
      @invitation.destroy
    end
  end

  def join
    @invitation = @space.invitations.find_by :token => params[:id]

    if logined?
      render :js => "Turbolinks.visit('#{dashboard_invitation_url(@space, @invitation)}');"
    else
      @user = User.new user_params
      if @user.save
        login_as @user
        @space.members << current_user
        @invitation.destroy
      end
    end
  end

  private

  def require_plan
    if @space.in_plan?(:free)
      render :js => "Turbolinks.visit('#{dashboard_members_url(@space)}');"
    end
  end

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/controllers/dashboard/members_controller.rb
class Dashboard::MembersController < Dashboard::BaseController
  before_filter :require_plan, :only => [:destroy]

  def index
  end

  def destroy
    @member = @space.members.find_by :name => params[:id]
    @space.members.delete @member
  end

  private

  def require_plan
    if @space.in_plan?(:free)
      render :js => "Turbolinks.visit('#{dashboard_members_url(@space)}');"
    end
  end
end

app/controllers/dashboard/orders_controller.rb
class Dashboard::OrdersController < Dashboard::BaseController
  skip_before_filter :require_logined, :require_space_access, :verify_authenticity_token, :only => [:alipay_notify]

  def index
    @orders = @space.orders.showable.desc(:created_at)
  end

  def new
    @order = Order.new
  end

  def create
    @order = @space.orders.new order_param.merge(:plan => :base, :price => 10)

    case @order.quantity
    when 6
      @order.discount = -10
    when 12
      @order.discount = -20
    end

    if [1, 6, 12].include?(@order.quantity) && @order.save
      redirect_to @order.pay_url
    else
      render :new
    end
  end

  def show
    @order = @space.orders.find params[:id]

    callback_params = params.except(*request.path_parameters.keys)
    if callback_params.any? && Alipay::Sign.verify?(callback_params)
      if @order.paid? || @order.completed?
        flash.now[:success] = I18n.t('order_paid_message')
      elsif @order.pending?
        flash.now[:info] = I18n.t('order_pending_message')
      end
    end
  end

  def alipay_notify
    notify_params = params.except(*request.path_parameters.keys)
    if Alipay::Notify.verify?(notify_params)
      @order = Order.find params[:out_trade_no]

      case params[:trade_status]
      when 'WAIT_BUYER_PAY'
        @order.update_attribute :trade_no, params[:trade_no]
        @order.pend
      when 'TRADE_FINISHED'
        need_mail = @order.pending?
        @order.complete
        SystemMailer.delay.order_payment_success(@order.id.to_s) if need_mail
      when 'TRADE_CLOSED'
        @order.cancel
        SystemMailer.delay.order_cancel(@order.id.to_s)
      when 'WAIT_SELLER_SEND_GOODS'
        @order.pay
        @order.send_good
        SystemMailer.delay.order_payment_success(@order.id.to_s)
      else
        # do nothing
      end

      AlipayNotify.create(
        :verify => true,
        :order  => @order,
        :params => notify_params
      )

      render :text => 'success'
    else
      AlipayNotify.create(
        :verify => false,
        :params => notify_params
      )

      render :text => 'error'
    end
  end

  private

  def order_param
    params.require(:order).permit(:quantity)
  end
end

app/controllers/ui/dashboard_controller.rb
class Ui::DashboardController < ApplicationController
  layout 'dashboard'
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def articles_is_end?(articles)
    articles.options[:skip].to_i + articles.to_a.count >= articles.count
  end

  def article_format_body(text)
    sanitize text, :tags => %w(p br img h1 h2 h3 h4 blockquote pre code b i strike u a ul ol li), :attributes => %w(href src id)
  end

  def article_summary_body(text)
    doc = Nokogiri::HTML::DocumentFragment.parse(text)
    simple_format truncate(doc.css('p').map(&:text).join("\n\n").to_s, :length => 140)
  end

  def article_remove_h1(text)
    doc = Nokogiri::HTML::DocumentFragment.parse(text)
    doc.css('h1').first.try(:remove)
    doc.to_s
  end
end

app/views/dashboard/articles/_article.html.slim
- cache [@space.name, article, I18n.locale] do
  li.article id=("article-#{article.token}") data-id=(article.token)
    .article-select
      i.icon-check-status
    .article-info
      a.title href=(edit_dashboard_article_path(:id => article))
        = article.title
      .quiet
        - if article.last_edit_user
          = article.last_edit_user.display_name
        - else
          = article.user.display_name
        '
        | 编辑于
        '
        = l article.updated_at, :format => :short

    - if article.publish?
      a.article-link href=(site_article_url(:id => article, :urlname => article.urlname, :host => @space.host, :protocol => 'http')) target='_blank'
        i.icon-external-link

app/views/dashboard/articles/_articles.html.slim
- if @articles.any?
  = render :partial => 'article', :collection => @articles
  - if @articles.total_pages > 1
    .inner
      = paginate @articles, :theme => :dashboard
- else
  li.inner.empty-message
    = t '.no_articles'

app/views/dashboard/articles/batch_update.js.erb
Turbolinks.visit("<%= request.referer %>");

app/views/dashboard/articles/edit.html.slim
= render :partial => 'dashboard/articles/edit/edit_topbar'
#editwrap
  .main
    = render :partial => 'dashboard/articles/edit/toolbar'
    #editarea
      .scrollable
        .editor-container
          article.article contentEditable="true" spellcheck="false" data-id=(@article.token) data-save-count=(@article.save_count) data-urlname=(@article.urlname) data-status=(@article.status) class=(@article.new_record? ? 'init' : nil) data-space=(@space.to_param) data-is-workspace=(@space.members.count > 1) data-current-user-name=(current_user.name)
            = article_format_body @article.body
      #alert-messages
      #readonly-message
        = t '.readonly_mode'

  .sidebar
    #history
      .toolbar.clearfix
        .pull-left
          .label
            i.icon-time
            '
            = t '.history_versions'
        ul.toolbar-buttons.pull-right
          li
            a.close-button.toolbar-button href="#close-history" title=(t '.return_newest_version')
              i.icon-remove
      .content
        .scrollable
          nav
            ul#versions
          - if @space.in_plan?(:free)
            .message
              = t '.version_limit'
              = link_to t('.need_more_version'), dashboard_billing_path

= render 'dashboard/articles/edit/urlname_modal'
= render 'dashboard/articles/edit/help_modal'
= render 'dashboard/share/image_uploader_modal'
= render 'dashboard/share/link_creator_modal'

app/views/dashboard/articles/empty_trash.js.erb
$('.articles .article').remove();
AlertMessage.show({
  text: '<%= t 'success' %>',
  type: 'success',
  timeout: 1500
});

app/views/dashboard/articles/index.html.slim
- append_title t('.articles')

- content_for :topbar do
  #normal-nav.clearfix class=('searching' if params[:query].present?)
    ul.topbar-nav.pull-left
      = render 'dashboard/share/sidebar'
      li.topbar-nav-item.show-on-tablet.hide-on-searching
        .dropdown
          a.dropdown-toggle
            - case params[:status]
            - when 'draft'
              = t '.drafted'
            - when 'publish'
              = t '.published'
            - else
              = t '.all'
          ul.dropdown-menu
            li
              a href=(dashboard_root_path(:status => nil))
                = t '.all'
            li
              a href=(dashboard_root_path(:status => 'draft'))
                = t '.drafted'
            li
              a href=(dashboard_root_path(:status => 'publish'))
                = t '.published'

      li.topbar-nav-item.hide-on-tablet class=('actived' if params[:status].blank? && params[:query].blank?)
        a href=(dashboard_root_path(:status => nil))
          = t '.all'
      li.topbar-nav-item.hide-on-tablet class=('actived' if params[:status] == 'draft')
        a href=(dashboard_root_path(:status => 'draft'))
          = t '.drafted'
      li.topbar-nav-item.hide-on-tablet class=('actived' if params[:status] == 'publish')
        a href=(dashboard_root_path(:status => 'publish'))
          = t '.published'
      - unless @space.in_plan?(:free)
        li.topbar-nav-item.show-on-tablet.hide-on-searching
          a.search-toggle
            i.icon-search
        li.topbar-nav-item.search.hide-on-tablet
          = form_tag dashboard_root_path, :method => :get, :class => 'search-form', :id => 'search-form', :data => { 'reset-url' => dashboard_root_path(:status => params[:status]) } do
            i.icon-search
            = search_field_tag 'query', params[:query], :class => 'search-input', :placeholder => '搜索', :tabindex => 1, :autocomplete => 'off', :autofocus => (params[:query].present? ? true : nil), :id => 'search-input'
            button.search-close type="reset" tabindex='2'
              i.icon-remove

    ul.topbar-nav.pull-right
      li.topbar-nav-item
        a href=("http://#{@space.host}") target="_blank"
          i.icon-external-link
          span.hide-on-small-screen
            '
            = t '.view'
      - if @space.in_plan?(:free)
        li.topbar-nav-item
          a href=(dashboard_billing_path)
            i.icon-level-up
            span.hide-on-small-screen
              '
              = t '.upgrade'
      li.topbar-nav-item
        a href=(new_dashboard_article_path)
          i.icon-plus
          span.hide-on-mobile
            '
            = t '.new_article'
      = render 'dashboard/share/config_menu'

  #toolbar.clearfix.hide
    ul.topbar-nav.pull-left
      li.topbar-nav-item
        a.close-button.min
          i.icon-remove
      li.topbar-nav-item.text
        span#selected-count 0
        '
        = t '.items'
    ul.topbar-nav.pull-right
      li.topbar-nav-item
        a.select-all-button.min
          i.icon-check-status
          '
          = t '.select_all'
      li.topbar-nav-item.hide-on-mobile
        a href=(batch_publish_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true"
          = t '.publish'
      li.topbar-nav-item.hide-on-mobile
        a href=(batch_draft_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true"
          = t '.draft'
      li.topbar-nav-item.hide-on-mobile
        a href=(batch_trash_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true"
          = t '.trash'
      li.topbar-nav-item.show-on-mobile
        .dropdown
          a.dropdown-toggle
            i.icon-wrench
          ul.dropdown-menu.align-right.last
            li
              a href=(batch_publish_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true"
                = t '.publish'
            li
              a href=(batch_draft_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true"
                = t '.draft'
            li
              a href=(batch_trash_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true"
                = t '.trash'

.main-section
  ul#articles.articles
    = render 'articles'

app/views/dashboard/articles/index.js.erb
$('#articles').html('<%= j render('articles') %>');

app/views/dashboard/articles/trashed.html.slim
- append_title t('.trashed')

- content_for :topbar do
  #normal-nav
    ul.topbar-nav.pull-left
      = render 'dashboard/share/sidebar'
      li.topbar-nav-item.text
        = t '.trashed'

    ul.topbar-nav.pull-right
      = render 'dashboard/share/config_menu'

  #toolbar.clearfix.hide
    ul.topbar-nav.pull-left
      li.topbar-nav-item
        a.close-button.min
          i.icon-remove
      li.topbar-nav-item.text
        span#selected-count 0
        '
        = t '.items'
    ul.topbar-nav.pull-right
      li.topbar-nav-item
        a.select-all-button.min
          i.icon-check-status
          '
          = t '.select_all'
      li.topbar-nav-item
        a href=(batch_restore_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true"
          = t '.restore'
      li.topbar-nav-item.hide-on-mobile
        a href=(batch_destroy_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true" data-confirm=(t '.destroy_confirm')
          = t '.completely_remove'
      li.topbar-nav-item.hide-on-mobile
        a href=(trashed_dashboard_articles_path) data-remote="true" data-method="delete" data-confirm=(t '.empty_trash_confirm')
          = t '.empty_trash'
      li.topbar-nav-item.show-on-mobile
        .dropdown
          a.dropdown-toggle
            i.icon-wrench
          ul.dropdown-menu.align-right.last
            li
              a href=(batch_destroy_dashboard_articles_path) data-remote="true" data-method="put" data-batch="true" data-confirm=(t '.destroy_confirm')
                = t '.completely_remove'
            li
              a href=(trashed_dashboard_articles_path) data-remote="true" data-method="delete" data-confirm=(t '.empty_trash_confirm')
                = t '.empty_trash'

.main-section
  - unless @articles.empty?
    ul#articles.articles
      = render :partial => 'article', :collection => @articles
    - if @articles.total_pages > 1
      .inner
        = paginate @articles, :theme => :dashboard
  - else
    .inner.empty-message
      = t '.no_articles'